Init:
  winget:
    - "gerardog.gsudo"
  modules:
    - "NuGet"
    - "PowerShellGet"
    # - "Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted"

Core:
  modules:
    - "PSScriptTools"
    - "Terminal-Icons"
    - "PSReadLine"
    - "PSWindowsUpdate"
    - "PSWritePDF"
  winget:
    - "M2Team.NanaZip"
    - "Git.Git"
    - "9WZDNCRD29V9"
    - "Microsoft.VisualStudioCode"
    - "Microsoft.PowerToys"
    - "KeePassXCTeam.KeePassXC"
    - "restic.restic"
    - "Obsidian.Obsidian"
    - "Google.Chrome"
    - "Mathpix.MathpixSnippingTool"
    - "Microsoft.WindowsTerminal"
    - "Spotify.Spotify"
    - "Google.GoogleDrive"
    - "JanDeDobbeleer.OhMyPosh"
    - "JAMSoftware.TreeSize.Free"

Messengers:
  winget:
    - "Discord.Discord"
    - "OpenWhisperSystems.Signal"
    - "Mozilla.Thunderbird"
    - "9NKSQGP7F2NH"

ProgrammingTools:
  winget:
    - "Inkscape.Inkscape"
    - "MiKTeX.MiKTeX"
    - "StrawberryPerl.StrawberryPerl"
    - "Python.Python.3.13"
    - "Rufus.Rufus"
    - "MathWorks.MATLABRuntime"
    - "AnalogDevices.LTspice"
    - "MSYS2.MSYS2"

Games:
  winget:
    - "Playnite.Playnite"
    - "Blizzard.BattleNet"
    - "Valve.Steam"
    - "Ubisoft.Connect"
    - "Orbmu2k.NvidiaProfileInspector"
    - "ElectronicArts.EADesktop"
    - "Logitech.GHUB"
    - "NVIDIA.GeForceExperience"
    - "RiotGames.Valorant"
    - "EpicGames.EpicGamesLauncher"
    - "9PMQSL444HLF"
    - "GOG.Galaxy"
